//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int Ref_Prod { get; set; }
        public string Designation { get; set; }
        public double Money { get; set; }
        public int Qte_Stock { get; set; }
    }
}
